Traceback (most recent call last):
  File "/home/zejiany/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/zejiany/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/zejiany/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/zejiany/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/zejiany/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/zejiany/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import sys
# sys.path.append("../../utils")
from utils.generate_field import *
from utils.visualize import *
# from visualize import *
import numpy as np
from pathlib import Path
from matplotlib.gridspec import GridSpec
import matplotlib.ticker as tick

result_dir = '/home/zyou6474/Projects/lesgo_adjoint_tutorial_bundle/tests/5_validation'
nk=3

# HPC Options ['Fermi', ]
server = 'Fermi'

if server=='Fermi':
    ic_dir = '/home/zyou6474/Projects/lesgo_adjoint_tutorial_bundle/tests/inputs/'
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;66;03m# import sys[39;00m
[1;32m      2[0m [38;5;66;03m# sys.path.append("../../utils")[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgenerate_field[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvisualize[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      5[0m [38;5;66;03m# from visualize import *[39;00m

[0;31mModuleNotFoundError[0m: No module named 'utils'

